apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "lab-argo.fullname" . }}
  labels:
    app: {{ include "lab-argo.name" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "lab-argo.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "lab-argo.name" . }}
    spec:
      containers:
        - name: nginx
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 80
